const employeesData = [
  {
    name: "Amit Sharma",
    email: "amit.sharma@company.com",
    department: "Engineering",
    designation: "Software Engineer",
    base_salary: 60000,
    joining_date: new Date("2022-03-15"),
  },
  {
    name: "Priya Verma",
    email: "priya.verma@company.com",
    department: "HR",
    designation: "HR Executive",
    base_salary: 45000,
    joining_date: new Date("2021-07-10"),
  },
  {
    name: "Rahul Mehta",
    email: "rahul.mehta@company.com",
    department: "Engineering",
    designation: "Backend Developer",
    base_salary: 65000,
    joining_date: new Date("2023-01-05"),
  },
  {
    name: "Sneha Reddy",
    email: "sneha.reddy@company.com",
    department: "Finance",
    designation: "Accountant",
    base_salary: 50000,
    joining_date: new Date("2020-11-20"),
  },
  {
    name: "Vikram Singh",
    email: "vikram.singh@company.com",
    department: "Engineering",
    designation: "Frontend Developer",
    base_salary: 62000,
    joining_date: new Date("2022-09-12"),
  },
  {
    name: "Neha Gupta",
    email: "neha.gupta@company.com",
    department: "Marketing",
    designation: "Marketing Manager",
    base_salary: 70000,
    joining_date: new Date("2019-06-01"),
  },
  {
    name: "Arjun Patel",
    email: "arjun.patel@company.com",
    department: "Engineering",
    designation: "DevOps Engineer",
    base_salary: 68000,
    joining_date: new Date("2023-04-18"),
  },
  {
    name: "Kavita Nair",
    email: "kavita.nair@company.com",
    department: "HR",
    designation: "HR Manager",
    base_salary: 72000,
    joining_date: new Date("2018-02-25"),
  },
  {
    name: "Rohit Das",
    email: "rohit.das@company.com",
    department: "Support",
    designation: "Support Engineer",
    base_salary: 42000,
    joining_date: new Date("2024-01-08"),
  },
  {
    name: "Pooja Iyer",
    email: "pooja.iyer@company.com",
    department: "Finance",
    designation: "Financial Analyst",
    base_salary: 56000,
    joining_date: new Date("2021-10-14"),
  },
  {
    name: "Manish Kumar",
    email: "manish.kumar@company.com",
    department: "Engineering",
    designation: "Tech Lead",
    base_salary: 90000,
    joining_date: new Date("2017-05-30"),
  },
  {
    name: "Anjali Desai",
    email: "anjali.desai@company.com",
    department: "Marketing",
    designation: "SEO Specialist",
    base_salary: 48000,
    joining_date: new Date("2022-08-22"),
  },
  {
    name: "Suresh Yadav",
    email: "suresh.yadav@company.com",
    department: "Operations",
    designation: "Operations Manager",
    base_salary: 75000,
    joining_date: new Date("2019-12-11"),
  },
  {
    name: "Meera Joshi",
    email: "meera.joshi@company.com",
    department: "Engineering",
    designation: "QA Engineer",
    base_salary: 52000,
    joining_date: new Date("2023-02-02"),
  },
  {
    name: "Deepak Mishra",
    email: "deepak.mishra@company.com",
    department: "Engineering",
    designation: "Full Stack Developer",
    base_salary: 70000,
    joining_date: new Date("2021-03-27"),
  },
  {
    name: "Ritika Kapoor",
    email: "ritika.kapoor@company.com",
    department: "HR",
    designation: "Recruiter",
    base_salary: 43000,
    joining_date: new Date("2024-05-16"),
  },
  {
    name: "Karan Malhotra",
    email: "karan.malhotra@company.com",
    department: "Sales",
    designation: "Sales Executive",
    base_salary: 47000,
    joining_date: new Date("2020-07-19"),
  },
  {
    name: "Divya Menon",
    email: "divya.menon@company.com",
    department: "Finance",
    designation: "Finance Manager",
    base_salary: 82000,
    joining_date: new Date("2018-09-09"),
  },
  {
    name: "Aditya Roy",
    email: "aditya.roy@company.com",
    department: "Engineering",
    designation: "System Architect",
    base_salary: 95000,
    joining_date: new Date("2016-04-04"),
  },
  {
    name: "Nikhil Jain",
    email: "nikhil.jain@company.com",
    department: "Support",
    designation: "Customer Support",
    base_salary: 40000,
    joining_date: new Date("2023-11-01"),
  },
];

export default employeesData;